export const groData = [
    {
        id:1,
        model:"TATA Salt",
        desc:"1 kg Pack",
        price: 25,
        image:"salt",
        qty:1,
    },
    {
        id:2,
        model:"OREO",
        desc:"150g Pack",
        price: 30,
        image:"oreo",
        qty:1,
    },
    {
        id:3,
        model:"Maggi",
        desc:"128g Pack",
        price: 28,
        image:"maggi",
        qty:1,
    },
    {
        id:4,
        model:"Carrot",
        desc:"1 Kg Pack",
        price: 35,
        image:"carrot",
        qty:1,
    },
    {
        id:5,
        model:"Tomato",
        desc:"1 Kg Pack",
        price: 15,
        image:"tomato",
        qty:1,
    },
]